(defpackage :robot-simulator
  (:use :cl)
  (:export :+north+ :+east+ :+south+ :+west+ :execute-sequence
           :robot :robot-position :robot-bearing :make-robot))

(in-package :robot-simulator)

(defvar +north+ 'north)
(defvar +east+ 'east)
(defvar +south+ 'south)
(defvar +west+ 'west)
(defvar *bearing* +north+)


(defun make-robot ( &key (position '(0 . 0)) (bearing +north+))
  (format t "position: ~A~%" position)
  (format t "bearing: ~A~%" bearing)
  (list :pos position
        :bear bearing)
  )

(defun robot-position (robot)
  (getf robot :pos))

(defun robot-bearing (robot)
  (getf robot :bear))

(defun advance (robot)
  (format t "robot start state: ~A~%" robot)
  (format t "robot bearing: ~A~%" (getf robot :bear))  
  (case (getf robot :bear)
     ((#.+north+)
     (incf (cdr (getf robot :pos)))
     )
     ((#.+south+)
     (decf (cdr (getf robot :pos)))
     )
     ((#.+east+)
     (incf (car (getf robot :pos)))
     )
     ((#.+west+)
     (decf (car (getf robot :pos)))
     )
    (otherwise t)
    )
  (format t "robot end state: ~A~%" robot)   
  robot
  )

(defun turn-left (robot)
  (case (getf robot :bear)
     ((#.+north+)
     (format t "turn to west~%")
     (setf (getf robot :bear) +west+)
     )
     ((#.+west+)
     (format t "turn to south~%")
     (setf (getf robot :bear) +south+)
     )
     ((#.+south+)
     (format t "turn to east~%")
     (setf (getf robot :bear) +east+)
     )
     ((#.+east+)
     (format t "turn to north~%")
     (setf (getf robot :bear) +north+)
     )
    (otherwise (format t "no action~%") nil)
    ) 
  robot
  )

(defun turn-right (robot)
  (case (getf robot :bear)
     ((#.+north+)
     (setf (getf robot :bear) +east+)
     )
     ((#.+east+)
     (setf (getf robot :bear) +south+)
     )
     ((#.+south+)
     (setf (getf robot :bear) +west+)
     )
     ((#.+west+)
     (setf (getf robot :bear) +north+)
     )
    (otherwise (format t "no action~%") nil)
    )
  (format t "robot end state: ~A~%" robot)  
  robot
  )

(defun execute-sequence (robot seq) 
  (if (zerop (length seq)) 
      ;do
      robot
      ;else
      (case (char seq 0)
        ((#\A)
        (setf robot (advance robot))
        (execute-sequence robot (subseq seq 1))
        )
        ((#\L)
        (setf robot (turn-left robot))
        (execute-sequence robot (subseq seq 1))
        )
        ((#\R)
        (setf robot (turn-right robot))
        (execute-sequence robot (subseq seq 1))
        )
        (otherwise nil)
        )
     ))
