(defpackage :diamond
  (:use :cl)
  (:export :rows))

(in-package :diamond)
       (defun rows (letter)
  (let* ((letidx (- (char-code (char-upcase letter)) (char-code #\A)))
         (letspan nil)
         (maxspan 0)
         (crow "")
         (res nil))
    (dotimes (n (1+ letidx))
      (setf maxspan (+ (* 2 n) 1))         
      (setf letspan (append letspan (list maxspan )))         
      )
    (do* ((idxx 1 (+ idxx 2))
         (ch #\A (code-char (1+ (char-code ch))))
          (lix1 (floor (/ maxspan 2)) (1- lix1))
          (lix2 (floor (/ maxspan 2)) (1+ lix2))          
          )
         ((= idxx (+ maxspan 2)) res)
      (setf crow (make-string maxspan :initial-element #\Space))
      (setf (char crow lix1) ch )
      (setf (char crow lix2) ch )
      (setf res (append res (list crow)))
      )
    (setf res (append res (cdr (reverse res))))
    )
  )
