(defpackage :book-store
  (:use :cl)
  (:export :calculate-price))

(in-package :book-store)

(defun test-bag (alist n)
  (if (>= (reduce #'+ (mapcar #'(lambda (x) (if (> (cdr x) 0) 1 0)) alist)) n) t nil))

(defun sum-bag (alist)
  (reduce #'+ (mapcar #'(lambda (x) (cdr x)) alist))
  )

(defun reduce-bag (alist n reslist)
  (cond ((null alist) reslist)
        ((= n 0) (reduce-bag (cdr alist) n (append reslist (list (car alist)))))
        ((> (cdar alist) 0) (reduce-bag (cdr alist) (1- n) (append reslist (list (cons (caar alist) (1- (cdar alist)))))))
        (t (reduce-bag (cdr alist) n (append reslist (list (car alist)))))
        ))

(defun get-n (alist n)
  (do ((reslist (copy-list  alist))
       (pc 0 (1+ pc)))
      ((not (test-bag alist n)) (values  reslist pc))
    (setf reslist (reduce-bag alist n '()))
    (setf alist reslist)
      )
  )

(defun get-n-down (alist n clist &key (db nil))
  (if db (format t "on entry: alist: ~A  n: ~A  clist: ~A ~%" alist n clist))
  (if (>= n 2)
      (multiple-value-bind (rlist ct) (get-n alist n )
        ;(format t "rlist: ~A ct: ~A ~%" rlist ct)
        (setf clist (append clist (list ct)))
        (get-n-down rlist (1- n) clist :db db)
        )
      (values clist alist)))

(defun get-price (dlist n reslist &key (db nil))
  (if db  (format t "~A ~A ~A ~%" dlist n reslist))
  (let ((discount '(0 0 0.05 0.10 0.20 0.25))
        (idx (copy-list dlist))
        (subtotal 0)
        (disc 0)
        (price 0))
    (loop for i from n downto 2 do
          (setf subtotal  (* i (car idx) 800))
          (if db  (format t "n: ~A  subtotal(1): ~A " i subtotal))
          (setf disc (- 1.00 (nth i discount)))
          (if db  (format t "n: ~A  disc       : ~A " i disc))
          (setf subtotal (* subtotal disc))
          (if db  (format t "n: ~A  subtotal(2): ~A " i subtotal))
          (setf price (+ price subtotal))
          (if db  (format t "price: ~A~%" price))
          (setf idx (cdr idx))
          )
    (setf subtotal (sum-bag reslist))
    (setf subtotal (* subtotal 800))
    (setf price (round (+ price subtotal)))
    (if db (format t "final price: ~A~%" price))
    price
    )
  )

(defun sort-assoc-list (alist)
  (sort (copy-list alist) ; Use `copy-list` to avoid modifying the original list
        (lambda (x y)
          (> (cdr x) (cdr y))))  
  )

(defun calculate-price (basket &key (db nil))
  (let (
        (books-count (copy-list '((1 . 0) (2 . 0) (3 . 0) (4 . 0) (5 . 0))))
        (prices nil)
        (tprice 0)
        )                                               
    (mapcar #'(lambda (x) (setf (cdr x) 0)) books-count)
    (loop for book in basket do
          (let ((entry (assoc book books-count)))
            ;(format t "incrementing ~A entry~%" book)
            (setf (cdr entry) (1+ (cdr entry)))))
    (setf books-count (sort-assoc-list books-count))
    (if db (format t "~A~%~%" books-count))
    (multiple-value-bind (dlist reslist) (get-n-down books-count 5 '() :db db) 
      (setf tprice (get-price dlist 5 reslist :db db))
      (setf prices (append  prices (list tprice))))
    (multiple-value-bind (dlist reslist) (get-n-down books-count 4 '() :db db)
      (setf tprice (get-price dlist 4 reslist :db db))
      (setf prices (append  prices (list tprice))))
    (multiple-value-bind (dlist reslist) (get-n-down books-count 3 '() :db db)
      (setf tprice (get-price dlist 3 reslist :db db))
      (setf prices (append  prices (list tprice))))    
    (multiple-value-bind (dlist reslist) (get-n-down books-count 2 '() :db db) 
      (setf tprice (get-price dlist 2 reslist :db db))
      (setf prices (append  prices (list tprice))))
    (if db (format t "prices: ~A~%" prices))
    (reduce #'min prices)
    ))
