(defpackage :say
  (:use :cl)
  (:export :say))

(in-package :say)

(defvar *thash* (make-hash-table))

(defun setup-ones-thash (ht)
  (setf (gethash 0 ht) "zero")
  (setf (gethash 1 ht) "one")  
  (setf (gethash 2 ht) "two")  
  (setf (gethash 3 ht) "three")  
  (setf (gethash 4 ht) "four")  
  (setf (gethash 5 ht) "five")  
  (setf (gethash 6 ht) "six")  
  (setf (gethash 7 ht) "seven")  
  (setf (gethash 8 ht) "eight")  
  (setf (gethash 9 ht) "nine")  
  (setf (gethash 10 ht) "ten")  
  (setf (gethash 11 ht) "eleven")  
  (setf (gethash 12 ht) "twelve")  
  (setf (gethash 13 ht) "thirteen")  
  (setf (gethash 14 ht) "fourteen")  
  (setf (gethash 15 ht) "fifteen")  
  (setf (gethash 16 ht) "sixteen")  
  (setf (gethash 17 ht) "seventeen")  
  (setf (gethash 18 ht) "eighteen")  
  (setf (gethash 19 ht) "nineteen")  
  (setf (gethash 20 ht) "twenty")
  (setf (gethash 30 ht) "thirty")  
  (setf (gethash 40 ht) "forty")  
  (setf (gethash 50 ht) "fifty")  
  (setf (gethash 60 ht) "sixty")  
  (setf (gethash 70 ht) "seventy")  
  (setf (gethash 80 ht) "eighty")  
  (setf (gethash 90 ht) "ninety"))

(defun strcat (src add suff)
  (concatenate 'string src (format nil "~a~a" add suff)))

(defun render-group (num group)
  (let ((hundreds (floor (/ num 100)))
        (teens (floor (mod num 100)))
        (tens (* (floor (/ (mod num 100) 10)) 10))
        (ones (mod num 10))
        (outstr "")
        )
    (if (> hundreds 0)
        (setf outstr (strcat outstr (gethash hundreds *thash*) " hundred ")))
    (if  (= tens 10)
        (setf outstr (strcat outstr (gethash teens *thash*) "")))
    (if  (> tens 10)
        (setf outstr (strcat outstr (gethash tens *thash*) "")))
    (if (and (> tens 10) (> ones 0))
        (setf outstr (strcat outstr "-" "")))
    (if (and (/= tens 10) (> ones 0))
        (setf outstr (strcat outstr (gethash ones *thash*) " ")))
    (if (> (length group) 0)
        (setf outstr (strcat outstr group " ")))
    outstr
  ))
    

(defun say (number)
  (setup-ones-thash *thash*)
  (if (or (< number 0) (> number 999999999999)) nil
      (let* ((ones 0)
             (thousands 0)
             (millions  0)
             (billions  0)
             (res 0)
             (outstr ""))
        (setf ones (mod number 1000))
        (setf res (floor (/ number 1000)))
        (setf thousands (mod res 1000))
        (setf res (floor (/ res 1000)))
        (setf millions (mod res 1000))
        (setf res (floor (/ res 1000)))
        (setf billions (mod res 1000))

        (if (= number 0)
            (setf outstr "zero"))            
        (if (> billions 0)
            (setf outstr (concatenate 'string outstr (render-group billions "billion"))))
        (if (> millions 0)
            (setf outstr (concatenate 'string  outstr (render-group millions "million"))))
        (if (> thousands 0)
            (setf outstr (concatenate 'string outstr (render-group thousands "thousand"))))
        (if (> ones 0)
            (setf outstr (concatenate 'string  outstr (render-group ones "")))) 
        (setf outstr (string-trim '(#\space) outstr))
        outstr
        )
      ))


    
    

